# Site settings
title: Development containers
description: >
  Development containers documentation and specification page.

# baseurl: / # the subpath of your site, e.g. /blog/
assets: /assets
url: https://devcontainers.github.io # the base hostname & protocol for your site
git_address: https://github.com/devcontainers/devcontainers.github.io
git_edit_address: https://github.com/devcontainers/devcontainers.github.io/settings/pages/blob/gh-pages
theme_color: 2753E3

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - github-pages
  - jemoji
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
  - resources

timezone: Europe/Zurich

collections_dir: content
collections:
  en:
    output: true

defaults:
- scope:
    path: content/*/guides
  values:
    category: guide
    permalink: :collection/guides/:title
    layout: post
    sectionid: guide
- scope:
    path: content/*/implementors
  values:
    category: implementors
    layout: implementors
    sectionid: implementors
